<?php

require __DIR__ . '/../core/base.php';

DB::exec('DROP TABLE game');
DB::exec('DROP TABLE user_log');
DB::exec('DROP TABLE set_info');
DB::exec('DROP TABLE user');
include __DIR__ . '/../deploy/user.php';
include __DIR__ . '/../deploy/game.php';
include __DIR__ . '/../deploy/user_log.php';
include __DIR__ . '/../deploy/set_info.php';
DB::exec("INSERT INTO user (username, password) VALUES('1','123')");

$user_id = DB::select("SELECT id FROM user WHERE username = '1' LIMIT 1")[0]['id'];
echo 'user ';
dump($user_id);
echo "\n";
assert($user_id === 1);
echo "\n";
$game_id = Game::create($user_id);
echo 'create game ';
dump($game_id);
echo "\n";
assert($game_id === 1);
echo "\n";
echo 'start game ';
echo "\n";
assert(Game::start($user_id));
echo "\n";
$game_info = Game::getGameInfo($user_id);
echo 'game info ';
dump($game_info);
echo "\n";
assert($game_info);
echo "\n";
echo 'game is ready';
echo "\n";
assert(Game::isReady($game_info));
echo "\n";
echo 'start set ';
echo "\n";
assert(Set::start($game_id));
echo "\n";
echo 'set info ';
$set_info = Set::getSetInfo($user_id);
dump($set_info);
echo "\n";
assert($set_info);
echo "\n";
assert($set_info['log_info'][0]['ops'] === OP_INIT);
echo "\n";
echo '****************************************';
echo "\n";
echo 'starat OK ';
echo "\n";
echo '****************************************';
echo "\n";
// todo after set info start, there should be next setp with the game

echo 'user op init ';
echo "\n";
assert(Set::op($user_id, OP_INIT));
echo 'hand card ';
$set_info = Set::getSetInfo($user_id);
dump_card($set_info['log_info'][0]['hand']);
echo "\n";
assert(count($set_info['log_info'][0]['hand']) === 13,
	'hand card count ' . count($set_info['log_info'][0]['hand']));
echo 'user op ';
dump($set_info['log_info'][0]['ops']);
echo "\n";
assert($set_info['log_info'][0]['ops'] === OP_GET);
echo '****************************************';
echo "\n";
echo 'init OK ';
echo "\n";
echo '****************************************';
echo "\n";
echo 'user get ';
echo "\n";
assert(Set::op($user_id, OP_GET));
echo 'hand card ';
$set_info = Set::getSetInfo($user_id);
dump_card($set_info['log_info'][0]['hand']);
echo "\n";
assert(count($set_info['log_info'][0]['hand']) === 13,
	'hand card count ' . count($set_info['log_info'][0]['hand']));
echo 'user op ';
dump($set_info['log_info'][0]['ops']);
echo "\n";
assert($set_info['log_info'][0]['ops'] === OP_PUSH);
echo 'cur seq ';
dump($set_info['cur_seq']);
echo "\n";
assert($set_info['cur_seq'] === 0);
echo 'wait seq ';
dump($set_info['wait_seqs']);
echo "\n";
assert($set_info['wait_seqs'] === []);
echo 'wait card ';
dump_card([$set_info['wait_card']]);
echo "\n";
assert(isset($set_info['wait_card']));
echo "\n";
echo '****************************************';
echo "\n";
echo 'get OK ';
echo "\n";
echo '****************************************';
echo "\n";
echo 'user push ';
echo "\n";
assert(Set::op($user_id, OP_PUSH));
echo 'hand card ';
$set_info = Set::getSetInfo($user_id);
dump_card($set_info['log_info'][0]['hand']);
echo "\n";
assert(count($set_info['log_info'][0]['hand']) === 13,
	'hand card count ' . count($set_info['log_info'][0]['hand']));
echo 'user op ';
dump($set_info['log_info'][0]['ops']);
echo "\n";
assert($set_info['log_info'][0]['ops'] === OP_GET);
echo 'cur seq ';
dump($set_info['cur_seq']);
echo "\n";
assert($set_info['cur_seq'] === 0);
echo 'wait seq ';
dump($set_info['wait_seqs']);
echo "\n";
assert($set_info['wait_seqs'] === []);
echo 'wait card ';
dump_card([$set_info['wait_card']]);
echo "\n";
assert(isset($set_info['wait_card']));
echo "\n";
echo '****************************************';
echo "\n";
echo 'push OK ';
echo "\n";
echo '****************************************';
echo "\n";
